name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt update && apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            python3-pip \
            clang-format \
            doxygen \
            graphviz \
            libeigen3-dev \
            ros-humble-eigen3-cmake-module \
            ros-humble-rclcpp \
            ros-humble-std-msgs \
            ros-humble-sensor-msgs \
            ros-humble-nav-msgs \
            ros-humble-geometry-msgs \
            ros-humble-diagnostic-msgs \
            ros-humble-tf2-ros \
            ros-humble-ros2launch \
            ros-humble-ament-cmake \
            ros-humble-ament-cmake-gtest \
            ros-humble-ament-lint-auto \
            ros-humble-ament-lint-common \
            ros-humble-ament-cmake-cpplint \
            ros-humble-ament-cmake-cppcheck

      - name: Setup ROS 2 Environment and Dependencies
        run: |
          source /opt/ros/humble/setup.bash
          if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
            sudo rosdep init
          fi
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    strategy:
      fail-fast: false
      matrix:
        linter: [cpplint, uncrustify, xmllint]

    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7.0
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: mag_simulator_package
