name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: mag_simulator_package
          target-ros2-distro: humble
          vcs-repo-file-url: mag_simulator.repos
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              },
              "test": {
                "parallel-workers": 2
              }
            }
