name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble # ROS 2 Humble Docker Image

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt update && apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            python3-pip \
            clang-format \
            doxygen \
            graphviz \
            libeigen3-dev \
            ros-humble-eigen3-cmake-module \
            ros-humble-rclcpp \
            ros-humble-std-msgs \
            ros-humble-sensor-msgs \
            ros-humble-nav-msgs \
            ros-humble-geometry-msgs \
            ros-humble-diagnostic-msgs \
            ros-humble-tf2-ros \
            ros-humble-ros2launch \
            ros-humble-ament-cmake \
            ros-humble-ament-cmake-gtest \
            ros-humble-ament-lint-auto \
            ros-humble-ament-lint-common \
            ros-humble-ament-cmake-cpplint \
            ros-humble-ament-cmake-cppcheck \
            cppcheck

      - name: Setup ROS 2 Environment and Dependencies
        run: |
          source /opt/ros/humble/setup.bash
          [ -f /etc/ros/rosdep/sources.list.d/20-default.list ] || sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We exclude cppcheck due to https://github.com/ament/ament_lint/pull/345
        linter: [cpplint, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.6.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: mag_simulator_package
